### ISSUE TITLE
unable to find template

### ISSUE THREAD

**Issue by ahmadhc** [schmittjoh/JMSPaymentCoreBundle#100]
hey
 i have a little problem with my paymet bundle and i need your help:
my controller:
public function indexAction($id=0)
{
/........
        return $this->render('JMSPaymentCoreBundle:Demo:payment.html.twig',array('form' => $form->createView() , 'id' => $id));
    }

my routing.yml:
payment:
    pattern:  /payment
    defaults: { _controller: JMSPaymentCoreBundle:Demo:index }

and whe i make this url:
http://localhost/Symfony/web/app_dev.php/payment

i got this error:
Unable to find template "JMSPaymentCoreBundle:Demo:payment.html.twig".

any help please

**Comment by regularjack** [comment]
Closing since it's been a long time and this is not an issue with the bundle but a support request.
