### ISSUE TITLE
All quantities from decimal to integer?

### ISSUE THREAD

**Issue by gonzalovilaseca** [schmittjoh/JMSPaymentCoreBundle#110]
After using some cart systems I've noticed all prices are in cents and price fields are integers, wouldn't it be a good idea for this bundle to follow this approach?

The reason some cart systems store prices in cents is explained here: http://verraes.net/2011/04/fowler-money-pattern-in-php/

**Comment by regularjack** [comment]
Closing in favour of #141

**Comment by regularjack** [comment]
This will be fixed in a future major release. For the moment, the documentation now includes a [guide](http://jmspaymentcorebundle.readthedocs.io/en/latest/guides/overriding_entity_mapping.html) on how to override entity mapping.
