### ISSUE TITLE
For anyone looking to show images instead of text

### ISSUE THREAD

**Issue by gonzalovilaseca** [schmittjoh/JMSPaymentCoreBundle#111]
This might help someone:
If you want to display images in the payment form selection all you have to do is add this:

{% form_theme form _self %}

{% block form_label %}
{% spaceless %}
    {% if label is not sameas(false) %}
        <img src="{{asset('bundles/yourbundle/images/'~label~'.jpg')}}">
    {% endif %}
{% endspaceless %}
{% endblock form_label %}

and then place an image with name the same name as the label under your images folder.

**Comment by regularjack** [comment]
Closing as not an issue.
