### ISSUE TITLE
Why is EntityManager closed on exception/rollback?

### ISSUE THREAD

**Issue by ruudk** [schmittjoh/JMSPaymentCoreBundle#123]
When I receive an `InvalidPaymentException` I'd like to use the EntityManager to find out more about the problem. But the EntityManager is already closed.

Why don't you use `$this->entityManager->clear();` instead of `$this->entityManager->close();` in the catch blocks inside `PluginController`?

**Comment by regularjack** [comment]
This will be addressed in #145. Closing.
