### ISSUE TITLE
Unit Tests Fail

### ISSUE THREAD

**Issue by iBiryukov** [schmittjoh/JMSPaymentCoreBundle#133]
Fatal error:  Class 'Symfony\Component\ExpressionLanguage\ExpressionLanguage' not found in /home/travis/build/schmittjoh/JMSPaymentCoreBundle/vendor/symfony/security-core/Symfony/Component/Security/Core/Authorization/ExpressionLanguage.php on line 22

**Comment by regularjack** [comment]
Fixed by #171
