### ISSUE TITLE
Entity field declaration

### ISSUE THREAD

**Issue by jonupton** [schmittjoh/JMSPaymentCoreBundle#141]
I can't figure out how to redefine the entity fields type and options. All I need to do is change the scale of all decimal fields from 5 to 2?

How I can do this? I've tried various methods to override/extend the entities and therefore override the column attributes but I can't find a method that works.

Any help would be greatly appreciated.

**Comment by regularjack** [comment]
Thanks for reporting this. The documentation now includes a [guide](http://jmspaymentcorebundle.readthedocs.io/en/latest/guides/overriding_entity_mapping.html) on how to override entity mapping.
