### ISSUE TITLE
Allow to override entity fields

### ISSUE THREAD

**Issue by bzis** [schmittjoh/JMSPaymentCoreBundle#146]
Hi,
I have a problem with entity amount fields. In the mapping they are decimal(10,5). But 5 digits for the number is not enough for me - I use decimal(9,2) for financial fields.
If the properties in entity fields are protected, not private, it would be possible to override them in own entities. 
Now the only way I see is to redefine all four entities with own complete mapping.
Or maybe there is a better way I don't see?

**Comment by regularjack** [comment]
Duplicate of #141

**Comment by regularjack** [comment]
The documentation now includes a [guide](http://jmspaymentcorebundle.readthedocs.io/en/latest/guides/overriding_entity_mapping.html) on how to override entity mapping.
