### ISSUE TITLE
Break console doctrine:database:create

### ISSUE THREAD

**Issue by Moinax** [schmittjoh/JMSPaymentCoreBundle#156]
Your JMSPaymentCoreBundle::boot method throws an exception when we run the console to create the database !

I think you should find another way (or at least catch the exception) to handle :

```php
if ($this->container->has('doctrine.dbal.default_connection')) {     
    $platform = $this->container->get('doctrine.dbal.default_connection')->getDatabasePlatform();
    $platform->markDoctrineTypeCommented(Type::getType(ExtendedDataType::NAME));
}
```

**Comment by tyx** [comment]
Anyone gets a solution ?

**Comment by greg0ire** [comment]
It actually breaks many other things, like for instance, proper exception handling when the database server is down. Instead of displaying a nice error page, the application shows a blank page.

**Comment by greg0ire** [comment]
@stof has [a solution](https://github.com/symfony/symfony/issues/15581#issuecomment-133039617)

**Comment by greg0ire** [comment]
My bad, I don't think it is a solution, it was more about extracting a part of the boot method (but the part that causes this bug still stays there).
