### ISSUE TITLE
Different behavior of create methods

### ISSUE THREAD

**Issue by makasim** [schmittjoh/JMSPaymentCoreBundle#16]
If you look at EntityPluginController you can find that `doCreatePayment` creates a new Payment instance (that's obvious) but `doCreatePaymentInstaction` persist sit PaymentInstration to database. 

P.S. It is not a real problem but makes the code less consistent.

**Comment by regularjack** [comment]
Thanks for the suggestion. I'm closing this issue since it's not really an issue and, as schmittjoh said, these are just internal methods.
