### ISSUE TITLE
Terms explanation

### ISSUE THREAD

**Issue by korotovsky** [schmittjoh/JMSPaymentCoreBundle#162]
Please help explain the terms:

 * What does `requestedAmount` and `processedAmount` mean in `FinancialTransaction` class? And what is the difference between them?
 * Who requests and who proceeds?
 * In which cases `requestedAmount` and `processedAmount` can be different?

**Comment by mheki** [comment]
hi,
it's a very old issue, but I'll try to explain.
- `requestedAmount` is the amount which user requested during checkout
- `processedAmount` is the amount which has been processed by the payment provider.

Example:
You wanted to buy a shirt for £30 using gift card as a payment method. (`requestedAmount == £30`).
You have only £20 available on your gift card, so the payment provider can reserve these funds and your `processedAmount == £20` is different than requested.

I hope it helps

**Comment by korotovsky** [comment]
@mheki Thank you! Yes, this is still actual for me :)
