### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by korotovsky** [schmittjoh/JMSPaymentCoreBundle#165]
Looks like there is no any activity since summer 2014. =/

**Comment by regularjack** [comment]
@schmittjoh It's sad to see this project dying, lots of people use it and there's already an ecosystem around it. If you need help with maintaining it I'm available, you can get in touch at <my-username>@gmail.com.

**Comment by regularjack** [comment]
Just a heads up that Johannes has given me access to this repo and I'll be helping with maintaining it from now on.
