### ISSUE TITLE
The source parameter is required

### ISSUE THREAD

**Issue by jeromelebleu26** [schmittjoh/JMSPaymentCoreBundle#166]
Hello, 

I'm trying to integrate JMLSPaymentBundle width RuudkPaymentStripeBundle but i've an error when i submit the form : 

"The source parameter is required"

An idea please ?

**Comment by regularjack** [comment]
This issue is specific to ruudk/PaymentStripeBundle, please open an issue there. This seems to be the same issue as ruudk/PaymentStripeBundle#5
