### ISSUE TITLE
Unknown column type "extended_payment_data"

### ISSUE THREAD

**Issue by hug963** [schmittjoh/JMSPaymentCoreBundle#173]
This commit https://github.com/schmittjoh/JMSPaymentCoreBundle/commit/8a52a58e7c5e6af6ae6ec02799fdee5a02b0e3c5 introduced this error everytime I launch the console or try to process a payment.

Symfony version: 2.8.9

> Unknown column type "extended_payment_data" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgot to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information.

**Comment by regularjack** [comment]
Thanks for reporting this @hug963. Can I ask how you know it's the mentioned commit that is causing the problem? Looking at the commit, the code should be functionally the same, only the order of execution changed.

@greg0ire Any idea what might be happening here?

**Comment by hug963** [comment]
I just checked the recent history for something that might have caused this error.
Checking out the commit just before removes the issue and checking out this commit brings it back...
And I agree that I can't really find something inside that might create the error.

What is really weird is that if I clear the symfony cache, I can do one request before the error appears again.

**Comment by greg0ire** [comment]
Hello again @hug963 ! Can you add a `die()` statement in the compiler pass, to see if it is executed when you get the error?

**Comment by greg0ire** [comment]
Also, can you provide a full stack trace (use `bin/console -vvv`)

**Comment by greg0ire** [comment]
Theory : the type might be "requested" before it is even registered (I can't see why or how), but the information I asked might help finding that out.

**Comment by hug963** [comment]
I installed the package on a fresh symfony 2.8 install to check if it was not the legacy site I was updating that was the problem, and I still get the error...

Console stack trace for doctrine:schema:update:

>   [Doctrine\DBAL\DBALException]
  Unknown column type "extended_payment_data" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If
   this error occurs during database introspection then you might have forgot to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseType
  s(). If the type name is empty you might have a problem with the cache or forgot some mapping information.


Exception trace:
 () at /path/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:228
 Doctrine\DBAL\DBALException::unknownColumnType() at /path/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/Type.php:172
 Doctrine\DBAL\Types\Type::getType() at /path/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php:200
 Doctrine\DBAL\Schema\MySqlSchemaManager->_getPortableTableColumnDefinition() at /path/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:820
 Doctrine\DBAL\Schema\AbstractSchemaManager->_getPortableTableColumnList() at /path/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:175
 Doctrine\DBAL\Schema\AbstractSchemaManager->listTableColumns() at /path/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:281
 Doctrine\DBAL\Schema\AbstractSchemaManager->listTableDetails() at /path/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:268
 Doctrine\DBAL\Schema\AbstractSchemaManager->listTables() at /path/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:1040
 Doctrine\DBAL\Schema\AbstractSchemaManager->createSchema() at /path/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:862
 Doctrine\ORM\Tools\SchemaTool->getUpdateSchemaSql() at /path/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/UpdateCommand.php:113
 Doctrine\ORM\Tools\Console\Command\SchemaTool\UpdateCommand->executeSchemaCommand() at /path/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/AbstractCommand.php:65
 Doctrine\ORM\Tools\Console\Command\SchemaTool\AbstractCommand->execute() at /path/vendor/doctrine/doctrine-bundle/Command/Proxy/UpdateSchemaDoctrineCommand.php:50
 Doctrine\Bundle\DoctrineBundle\Command\Proxy\UpdateSchemaDoctrineCommand->execute() at /path/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /path/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:863
 Symfony\Component\Console\Application->doRunCommand() at /path/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:192
 Symfony\Component\Console\Application->doRun() at /path/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:92
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /path/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:123
 Symfony\Component\Console\Application->run() at /path/app/console:29

**Comment by greg0ire** [comment]
What about the `die()` ?

**Comment by hug963** [comment]
The die() trick doesn't work.

The thing is that it works once when the cache is cleared and then it doesn't anymore.

So adding die in dev, it clears the cache first and I 'd never get the error anyway.

dirty solution with two "var_dump()":

```shell
$ rm -rf app/cache/*

$ php app/console doctrine:schema:update --force -vvv
/path/vendor/jms/payment-core-bundle/JMS/Payment/CoreBundle/JMSPaymentCoreBundle.php:39:
string(5) "build"
/path/vendor/jms/payment-core-bundle/JMS/Payment/CoreBundle/DependencyInjection/Compiler/RegisterExtendedDataTypePass.php:35:
string(28) "RegisterExtendedDataTypePass"
Nothing to update - your database is already in sync with the current entity metadata.

$ php app/console doctrine:schema:update --force -vvv


  [Doctrine\DBAL\DBALException]
  Unknown column type "extended_payment_data" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If
   this error occurs during database introspection then you might have forgot to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseType
  s(). If the type name is empty you might have a problem with the cache or forgot some mapping information.


Exception trace:
 () at /path/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:228
 Doctrine\DBAL\DBALException::unknownColumnType() at /path/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/Type.php:172
 Doctrine\DBAL\Types\Type::getType() at /path/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php:200
 Doctrine\DBAL\Schema\MySqlSchemaManager->_getPortableTableColumnDefinition() at /path/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:820
 Doctrine\DBAL\Schema\AbstractSchemaManager->_getPortableTableColumnList() at /path/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:175
 Doctrine\DBAL\Schema\AbstractSchemaManager->listTableColumns() at /path/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:281
 Doctrine\DBAL\Schema\AbstractSchemaManager->listTableDetails() at /path/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:268
 Doctrine\DBAL\Schema\AbstractSchemaManager->listTables() at /path/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:1040
 Doctrine\DBAL\Schema\AbstractSchemaManager->createSchema() at /path/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:862
 Doctrine\ORM\Tools\SchemaTool->getUpdateSchemaSql() at /path/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/UpdateCommand.php:113
 Doctrine\ORM\Tools\Console\Command\SchemaTool\UpdateCommand->executeSchemaCommand() at /path/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/AbstractCommand.php:65
 Doctrine\ORM\Tools\Console\Command\SchemaTool\AbstractCommand->execute() at /path/vendor/doctrine/doctrine-bundle/Command/Proxy/UpdateSchemaDoctrineCommand.php:50
 Doctrine\Bundle\DoctrineBundle\Command\Proxy\UpdateSchemaDoctrineCommand->execute() at /path/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /path/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:863
 Symfony\Component\Console\Application->doRunCommand() at /path/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:192
 Symfony\Component\Console\Application->doRun() at /path/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:92
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /path/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:123
 Symfony\Component\Console\Application->run() at /path/app/console:29

doctrine:schema:update [--complete] [--dump-sql] [-f|--force] [--em [EM]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>
```

You can see the first try works and both files are called.
The second try nothing is called and it fails...

**Comment by greg0ire** [comment]
I can reproduce the issue.

**Comment by greg0ire** [comment]
Doing any save in the compiler pass file temporarily solves the issue (by invalidating the cache, I guess).

**Comment by greg0ire** [comment]
I did not do exactly as @stof advised (I don't change the doctrine bundle config), this must be the problem.

**Comment by regularjack** [comment]
I was able to reproduce the issue too. There's clearly something weird that is cache-related going on since it works the first time.

@greg0ire What do you mean by "I don't change the doctrine bundle config"? Can you point to @stof's comment you mention?

**Comment by greg0ire** [comment]
Here the comment in question : https://github.com/symfony/symfony/issues/15581#issuecomment-133039617

**Comment by greg0ire** [comment]
I mean I don't change the doctrine dbal configuration , I register the type directly (but this does not change the container I guess). Trying that right now.

**Comment by greg0ire** [comment]
Ok so I have something that works for the type registration I guess the call to `setEncryptionService can be moved back to the boot() method, since it does not access the db.

**Comment by olufuwamichael** [comment]
In my case, I uninstalled the JMS bundle, deleted my cache but still had the message popping up. But I had couple of tables previously created by JMS bundle; once I deleted those everything was fine.

**Comment by rapaelector** [comment]
Form me I reinstall just jms like: 

composer require jms/payment-core-bundle

and it's resolve
