### ISSUE TITLE
Doctrine schema update shows 2 changes for extended_data columns

### ISSUE THREAD

**Issue by ruudk** [schmittjoh/JMSPaymentCoreBundle#201]
For some reason, every time I run `doctrine:schema:update`, 2 changes appear:
```
$ php app/console doctrine:schema:update --dump-sql
ALTER TABLE financial_transactions CHANGE extended_data extended_data LONGTEXT DEFAULT NULL COMMENT '(DC2Type:object)';
ALTER TABLE payment_instructions CHANGE extended_data extended_data LONGTEXT NOT NULL COMMENT '(DC2Type:object)';
```

When I run `php app/console doctrine:schema:update` to update my database it executes 2 queries:
```
$ php app/console doctrine:schema:update
Updating database schema...
Database schema updated successfully! "2" queries were executed
```

If I run `php app/console doctrine:schema:update --dump-sql` again, the changes appear:

```
$ php app/console doctrine:schema:update --dump-sql
ALTER TABLE financial_transactions CHANGE extended_data extended_data LONGTEXT DEFAULT NULL COMMENT '(DC2Type:object)';
ALTER TABLE payment_instructions CHANGE extended_data extended_data LONGTEXT NOT NULL COMMENT '(DC2Type:object)';
```

Is this related to JMSPaymentCoreBundle? Or is there an issue with Doctrine2?

**Comment by regularjack** [comment]
I just tested this and I don't have that issue so I assume it has something to do with your setup. 

Take a look at #57, namely this [comment](https://github.com/schmittjoh/JMSPaymentCoreBundle/issues/57#issuecomment-7275203) which appears to be the exact same issue.

If you manage to solve it, can you describe here how you did it so we can add it to the docs?

Thanks.

**Comment by regularjack** [comment]
Were you able to find a fix for the issue? It'd be very useful to add a fix to the docs.

**Comment by ruudk** [comment]
I still have no clue why this happens. I will debug it one day, and try to find the root cause.

**Comment by ruudk** [comment]
Apparently I was using an older version of this bundle. Fixed now!
