### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by j-mywheels** [schmittjoh/JMSPaymentCoreBundle#223]

**Comment by gustawdaniel** [comment]
Is this package still supported?

**Comment by schmittjoh** [comment]
@regularjack , are you still using/maintaining the bundle?

**Comment by j-mywheels** [comment]
Any progress @schmittjoh @regularjack about the support for symfony 4?

**Comment by regularjack** [comment]
@j-mywheels @schmittjoh Sorry for the radio silence. I started adding support for Symfony 4 a while back but it turned out to be more complex than expected and I haven't been able to invest the needed time. I've since picked it up again and hope to have news soon.

**Comment by regularjack** [comment]
I just released v1.4.0 which adds support for Symfony 4. Please see the [release notes](https://github.com/schmittjoh/JMSPaymentCoreBundle/releases/tag/1.4.0) for more information.
