### ISSUE TITLE
Is there a missing final step in your new example?

### ISSUE THREAD

**Issue by petesiss** [schmittjoh/JMSPaymentCoreBundle#25]
When following with your new example, it seems the final step is missing.

I make my order object, get sent to paypal, log in, confirm the details in paypals site, then I get returned to the return_url.... but what next? The payment is left then at "pending" with "action_required".

I think there is another step there where the plugin should hit paypal one more time to actually action the payment.

**Comment by ngodfraind** [comment]
For those who get this error, make sure you're doing the transaction in the right currency (paypal sandbox default is USD).
