### ISSUE TITLE
Has anyone implemented "GetExpressCheckoutDetails" to retrieve Shipping details?

### ISSUE THREAD

**Issue by dangraetzer** [schmittjoh/JMSPaymentCoreBundle#37]
I need to retrieve the shipping information that was entered into PayPal, however the Response object only returns the following data:

```
string 'array (
  'TOKEN' => 'EC-XXXXX,
  'TIMESTAMP' => '2012-05-22T03:19:53Z',
  'CORRELATIONID' => 'fd3aba347de6',
  'ACK' => 'Success',
  'VERSION' => '65.1',
  'BUILD' => '2860716',
)' (length=193)
```

Has anyone implemented GetExpressCheckoutDetails? http://www.paypalobjects.com/en_US/ebook/PP_NVPAPI_DeveloperGuide/expresscheckout.html#2063856

Thanks

**Comment by regularjack** [comment]
This issue is PayPal-specific so I'm closing it in favour of schmittjoh/JMSPaymentPaypalBundle#25
