### ISSUE TITLE
Call to undefined method getFormFactory()

### ISSUE THREAD

**Issue by djoo** [schmittjoh/JMSPaymentCoreBundle#71]
Hello,

I'm a beginner in Symfony 2. I try to implement your bundle in my application.
I follow the doc and install plugin correctly.
Now i want to creat the form jms_choose_payment_method but i have the error Call to undefined method getFormFactory()  :

$form = $this->getFormFactory()->create('jms_choose_payment_method', null, array(
				'amount'   => 10,
				'currency' => 'EUR',
				'default_method' => 'payment_paypal', // Optional
				'predefined_data' => array(
						'paypal_express_checkout' => array(
								'return_url' => $this->router->generate('payment_complete', array(
										'orderNumber' => $order->getOrderNumber(),
								), true),
								'cancel_url' => $this->router->generate('payment_cancel', array(
										'orderNumber' => $order->getOrderNumber(),
								), true)
						),
				),
		));

I think it's a problem with symfony, not your bundle, but i don't understand how escape at this error. Have you an idea ? I try a lot of use, but nothing :(

Thanks

**Comment by regularjack** [comment]
Fixed by #183
