### ISSUE TITLE
Add plugin

### ISSUE THREAD

**Issue by jmartos89** [schmittjoh/JMSPaymentCoreBundle#75]
good,

I'm implementing a new plugin, I have defined the entire structure to retrieve the service but this is not visible.

services.xml

<? xml version = "1.0">

<container xmlns = "http://symfony.com/schema/dic/services"
     xmlns: xsi = "http://www.w3.org/2001/XMLSchema-instance"
     xsi: schemaLocation = "http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">

<parameters>
<parameter key="payment.plugin.credit_card_checkout.class"> \ Test \ TPVBundle \ Plugin \ CreditCardPlugin </ parameter>

<parameter key="payment.form.credit_card_checkout.class"> \ Test \ TPVBundle \ Form \ CreditCardType </ parameter>
</ parameters>
<services>
<service id="payment.plugin.tpv" class="TPVPlugin">
<tag name="payment.plugin" />
</ service>

<service id="payment.plugin.credit_card_checkout" class="%payment.plugin.credit_card_checkout.class%">

<tag name="payment.plugin" />
</ service>

<service id="payment.plugin.credit_card_checkout_type" class="%payment.form.credit_card_checkout.class%">
name="form.type" <tag alias="credit_card_checkout" />
<tag name="payment.method_form_type" />
</ service>
</ services>
</ container>

When you call $ plugin = $ this-> get ('payment.plugin.credit_card_checkout');

I returned the plugin does not exist

**Comment by regularjack** [comment]
Please see the [docs](http://jmspaymentcorebundle.readthedocs.io/en/latest/plugins.html) for information on how to implement custom plugins.
