### ISSUE TITLE
[Gedmo\Exception\UnexpectedValueException] when updating database

### ISSUE THREAD

**Issue by vsergiu** [schmittjoh/JMSPaymentCoreBundle#78]
After installing the bundle and trying to update the database this error occurs:

```php
[Gedmo\Exception\UnexpectedValueException]
No mapping file found named 'JMS.Payment.CoreBundle.Entity.Credit.orm.xml'
for class 'JMS\Payment\CoreBundle\Entity\Credit'.
```

I can fix this modifying the core bundle, but maybe there is another quick fix which I am not aware of.

**Comment by regularjack** [comment]
The [setup instructions](http://jmspaymentcorebundle.readthedocs.io/en/latest/setup.html#create-database-tables) now mention that either `auto_mapping` must be enabled or the mapping files loaded explicitly. Closing.
