### ISSUE TITLE
Create new plugin

### ISSUE THREAD

**Issue by pdias** [schmittjoh/JMSPaymentCoreBundle#83]
Hello i try this:

<?php
namespace BankBundle\Plugin;

use JMS\Payment\CoreBundle\Model\ExtendedDataInterface;
use JMS\Payment\CoreBundle\Model\FinancialTransactionInterface;
use JMS\Payment\CoreBundle\Plugin\PluginInterface;
use JMS\Payment\CoreBundle\Plugin\AbstractPlugin;
use JMS\Payment\CoreBundle\Plugin\Exception\PaymentPendingException;
use JMS\Payment\CoreBundle\Plugin\Exception\FinancialException;
use JMS\Payment\CoreBundle\Plugin\Exception\Action\VisitUrl;
use JMS\Payment\CoreBundle\Plugin\Exception\ActionRequiredException;
use JMS\Payment\CoreBundle\Util\Number;

class BankPlugin extends AbstractPlugin
{
    public function processes($paymentSystemName)
    {
        return 'bank_transfer' === $paymentSystemName;
    }
}

My service.xml

<?xml version="1.0" ?>

<container xmlns="http://symfony.com/schema/dic/services"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">

    <parameters>
        <parameter key="payment.plugin.bank_transfer.class">BankBundle\Plugin\BankPlugin</parameter>
    </parameters>

    <services>
        <service id="payment.plugin.bank_transfer" class="%payment.plugin.bank_transfer.class%">
            <tag name="payment.plugin" />
        </service>
    </services>
</container>

But i catch this exception:

There is no plugin that processes payments for "bank_transfer". 

What i'm doing wrong?

Thanks

**Comment by regularjack** [comment]
Please see the [docs](http://jmspaymentcorebundle.readthedocs.io/en/latest/plugins.html) for information on how to implement custom plugins.
