### ISSUE TITLE
Custom Plugin Documentation bug

### ISSUE THREAD

**Issue by HectorLinares** [schmittjoh/JMSPaymentCoreBundle#92]
Seems to be an error in Custom Plugin documentation. 

Where it says:
services:
    credit_card_type:
        class: CreditCardType
        tags:
            - { name: form.type, alias: credit_card }
            - { name: payment.method_type }

I think its:
services:
    credit_card_type:
        class: CreditCardType
        tags:
            - { name: form.type, alias: credit_card }
            - { name: payment.method_form_type }

Note the "payment.method_form_type" difference

**Comment by regularjack** [comment]
Duplicate of #84
