### ISSUE TITLE
Try use allowed_methods option

### ISSUE THREAD

**Issue by hidabe** [schmittjoh/JMSPaymentCoreBundle#93]
I am trying use allowed_methods from $this->get('form.factory')->create('jms_choose_payment_method', null, array(

I have seen it in ChoosePaymentMethodType->buildForm,

But it dont work, it return: The option "allowed_methods" does not exist 

I think that it is bug

Thanks and regards

**Comment by regularjack** [comment]
I just tested and the `allowed_methods` option works as expected. Also, this options is now better explained in the [documentation](http://jmspaymentcorebundle.readthedocs.io/en/stable/accepting_payments.html#choosing-payment-methods).
