### ISSUE TITLE
Currency problem

### ISSUE THREAD

**Issue by htomi** [schmittjoh/JMSPaymentCoreBundle#94]
Hi,
 
There is a limit for an amount field in PaymentInstruction:
< field name="amount" type="decimal" scale="5" / >

PayPal is also limit this value ("a positive number which cannot exceed $10,000 USD in any currency").

I want to deposit 1 000 000 HUF (~5 000 USD), but the bundle convert it 9999,9999 (because the scale="5")

How can I solve this issue?

**Comment by regularjack** [comment]
Closing in favour of #141

**Comment by regularjack** [comment]
This will be fixed in a future major release. The documentation now includes a [guide](http://jmspaymentcorebundle.readthedocs.io/en/latest/guides/overriding_entity_mapping.html) on how to override entity mapping.
