### ISSUE TITLE
error in jmsCoreBundle.php

### ISSUE THREAD

**Issue by ahmadhc** [schmittjoh/JMSPaymentCoreBundle#99]
hello,
i am trying to configure jmsPaymentCoreBundle but i have this error and i dont undertand it, if anyone please can help me;
the error: Undefined class constant 'NAME' in C:\wamp\www\Symfony\src\JMS\CoreBundle\JMSCoreBundle.php on line 32

thz function:

public function boot()
    {
        if (false === Type::hasType(ExtendedDataType::NAME)) {
            ExtendedDataType::setEncryptionService($this->container->get('payment.encryption_service'));
            Type::addType(ExtendedDataType::NAME, 'JMS\Payment\CoreBundle\Entity\ExtendedDataType');
            
            if ($this->container->has('doctrine.dbal.default_connection')) {     
                $platform = $this->container->get('doctrine.dbal.default_connection')->getDatabasePlatform();
                $platform->markDoctrineTypeCommented(Type::getType(ExtendedDataType::NAME));
            }
        }
    }

**Comment by regularjack** [comment]
Not sure what was happening here but closing since `ExtendedDataType::NAME` is no longer referenced from `JMSPaymentCoreBundle.php`.
